### ISSUE TITLE
Continuous Integration support (or lack thereof)

### ISSUE THREAD

**Issue by nabijaczleweli** [tapio/rlutil#25]
You could use [TravisCI](https://travis-ci.org), which is trivial to set up.
I think the following `.travis.yml` would suffice:

```yaml
sudo: false
language: cpp
compiler:
  - gcc
  - clang

script: make
```
